FROM nginx:1.27.0-alpine

RUN apk update && apk upgrade && apk add openssl\
&& mkdir -p /etc/nginx/ssl\
&& mkdir -p /var/run/nginx

RUN openssl req -newkey rsa:4096 -days 365 -x509 -nodes \
-subj "/C=KR/ST=Seoul/L=Seoul/O=42Seoul/OU=tc/CN=nginx" \
-keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt\
&& rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf

STOPSIGNAL SIGQUIT

CMD ["nginx", "-g", "daemon off;"]