services:
  db:
    image: postgres:16.4-alpine3.20
    container_name: db
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    networks:
      - intra

  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    networks:
      - intra
    expose:
      - 6379

  backend:
    container_name: backend
    restart: unless-stopped
    build: ./backend
    command: >
      sh -c "
      pip install -r requirements.txt &&
      python manage.py makemigrations users &&
      python manage.py migrate users &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      daphne transcendence_backend.asgi:application --bind 0.0.0.0 --port 8000
      "
    volumes:
      - ./backend:/code
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=transcendence_backend.settings
      - PYTHONPATH=/code
    networks:
      - intra

  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - 443:443
    networks:
      - intra
    volumes:
      - ./frontend/static/html:/usr/share/nginx/html
      - ./frontend/static/images:/usr/share/nginx/images
      - ./backend/media:/usr/share/nginx/media # 미디어 파일을 위한 볼륨 추가

networks:
  intra:
    driver: bridge
