# 베이스 이미지
FROM python:3.9-slim
ENV PYTHONUNBUFFERED=1
# 작업 디렉토리 설정
WORKDIR /code

# 필요한 파일 복사
COPY requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /code/

# 명령어 설정
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]